[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "Serial Experiment Runner"
version = "1.1.1"

[tool.pytest.ini_options]
pythonpath = "."
addopts = ["--import-mode=importlib"]
